In [19]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 283 kB 7.6 MB/s eta 0:00:01
     |████████████████████████████████| 25.8 MB 99 kB/s s eta 0:00:01
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
filename = "iris"
data = pd.read_csv('iris', header=None)
data.columns = ["sepal_length","sepal_width",
                'petal_length','petal_width','species']
data.dropna(how='all', inplace=True)
data.head()

data

sepal_length  sepal_width  petal_length  petal_width         species
0             4.6          3.6           1.0          0.2     Iris-setosa
1             5.1          3.3           1.7          0.5     Iris-setosa
2             4.8          3.4           1.9          0.2     Iris-setosa
3             5.0          3.0           1.6          0.2     Iris-setosa
4             5.0          3.4           1.6          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
123           6.7          3.0           5.2          2.3  Iris-virginica
124           6.3          2.5           5.0          1.9  Iris-virginica
125           6.5          3.0           5.2          2.0  Iris-virginica
126           6.2          3.4           5.4          2.3  Iris-virginica
127           5.9          3.0           5.1          1.8  Iris-virginica

[128 rows x 5 columns]

In [3]:
keys = np.unique(data['label'])

grp = [[],[],[]]
counter = 0
for key in keys:
    grp[counter] = data[data["label"]==key]
    counter +=1

grp

[array([(4.6, 3.6, 1. , 0.2, b'Iris-setosa'),
        (5.1, 3.3, 1.7, 0.5, b'Iris-setosa'),
        (4.8, 3.4, 1.9, 0.2, b'Iris-setosa'),
        (5. , 3. , 1.6, 0.2, b'Iris-setosa'),
        (5. , 3.4, 1.6, 0.4, b'Iris-setosa'),
        (5.2, 3.5, 1.5, 0.2, b'Iris-setosa'),
        (5.2, 3.4, 1.4, 0.2, b'Iris-setosa'),
        (4.7, 3.2, 1.6, 0.2, b'Iris-setosa'),
        (4.8, 3.1, 1.6, 0.2, b'Iris-setosa'),
        (5.4, 3.4, 1.5, 0.4, b'Iris-setosa'),
        (5.2, 4.1, 1.5, 0.1, b'Iris-setosa'),
        (5.5, 4.2, 1.4, 0.2, b'Iris-setosa'),
        (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
        (5. , 3.2, 1.2, 0.2, b'Iris-setosa'),
        (5.5, 3.5, 1.3, 0.2, b'Iris-setosa'),
        (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
        (4.4, 3. , 1.3, 0.2, b'Iris-setosa'),
        (5.1, 3.4, 1.5, 0.2, b'Iris-setosa'),
        (5. , 3.5, 1.3, 0.3, b'Iris-setosa'),
        (4.5, 2.3, 1.3, 0.3, b'Iris-setosa'),
        (4.4, 3.2, 1.3, 0.2, b'Iris-setosa'),
        (5. , 3.5, 1.6, 0.6, b'Iri

In [32]:
plt.style.use("ggplot")
plt.rcParams["figure.figsize"] = (12,8)
sns.scatterplot(x = data.sepal_length, y=data.sepal_width,
               hue = data.species, style=data.species)

<AxesSubplot:xlabel='sepal_length', ylabel='sepal_width'>

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [33]:
def standardize_data(arr):
         
    '''
    This function standardize an array, its substracts mean value, 
    and then divide the standard deviation.
    
    param 1: array 
    return: standardized array
    '''    
    rows, columns = arr.shape
    
    standardizedArray = np.zeros(shape=(rows, columns))
    tempArray = np.zeros(rows)
    
    for column in range(columns):
        
        mean = np.mean(X[:,column])
        std = np.std(X[:,column])
        tempArray = np.empty(0)
        
        for element in X[:,column]:
            
            tempArray = np.append(tempArray, ((element - mean) / std))
 
        standardizedArray[:,column] = tempArray
    
    return standardizedArray

In [36]:
X = data.iloc[:, 0:4].values
y = data.species.values

X = standardize_data(X)

In [37]:
covariance_matrix = np.cov(X.T)



In [38]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)
print("Eigenvector: \n",eigen_vectors,"\n")
print("Eigenvalues: \n", eigen_values, "\n")

Eigenvector: 
 [[ 0.54195468  0.28223544  0.7361652   0.29101388]
 [-0.15960156  0.95880131 -0.20391757 -0.1168119 ]
 [ 0.59279435 -0.0224079  -0.11270889 -0.7971132 ]
 [ 0.57394018  0.02326138 -0.63543303  0.51601982]] 

Eigenvalues: 
 [2.81014583 1.00975107 0.18401015 0.02758902] 



In [39]:
variance_explained = []
for i in eigen_values:
     variance_explained.append((i/sum(eigen_values))*100)
        
print(variance_explained)

[69.70478903558468, 25.046559631306952, 4.564314274752067, 0.6843370583563083]


In [40]:
cumulative_variance_explained = np.cumsum(variance_explained)
print(cumulative_variance_explained)

[ 69.70478904  94.75134867  99.31566294 100.        ]


In [41]:
sns.lineplot(x = [1,2,3,4], y=cumulative_variance_explained)
plt.xlabel("Number of components")
plt.ylabel("Cumulative explained variance")
plt.title("Explained variance vs Number of components")

Text(0.5, 1.0, 'Explained variance vs Number of components')

In [42]:
projection_matrix = (eigen_vectors.T[:][:2]).T
print(projection_matrix)

[[ 0.54195468  0.28223544]
 [-0.15960156  0.95880131]
 [ 0.59279435 -0.0224079 ]
 [ 0.57394018  0.02326138]]


In [48]:
X_pca = X.dot(projection_matrix)
print(X_pca)


[[-3.30547862  1.02616785]
 [-2.34127585  0.47411931]
 [-2.75539837  0.59855201]
 [-2.5702957  -0.29748886]
 [-2.56815346  0.6796954 ]
 [-2.67440399  0.98739866]
 [-2.67116104  0.7461654 ]
 [-2.85355109  0.08234148]
 [-2.74566953 -0.12514777]
 [-2.33533074  0.82169219]
 [-2.99858946  2.4399058 ]
 [-2.79179859  2.79270915]
 [-2.79717332 -0.09191277]
 [-2.79965968  0.19340256]
 [-2.54621988  1.09565144]
 [-2.79717332 -0.09191277]
 [-3.08668835 -0.50416537]
 [-2.70150696  0.70961309]
 [-2.80183151  0.92322795]
 [-2.65462131 -2.16416176]
 [-3.16746694 -0.01889055]
 [-2.44484334  0.92896743]
 [-2.55077933  1.68118075]
 [-2.69772322 -0.36165957]
 [-2.82591779  1.67875858]
 [-2.99533605  0.05000162]
 [-2.68769031  1.50782164]
 [-2.76575628  0.43323167]
 [ 0.83250432  0.88702825]
 [ 0.43510773  0.6822649 ]
 [ 0.96154375  0.60975169]
 [-0.15825018 -1.8174191 ]
 [ 0.70130352 -0.25454073]
 [-0.03948038 -0.54095648]
 [ 0.48336857  0.89026316]
 [-1.10916664 -1.78579353]
 [ 0.56470707  0.01661022]
 

array([-3.30547862,  1.02616785])

In [49]:
data['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [51]:
for species in data['species'].unique():
    sns.scatterplot(X_pca[y==species, 0],
                   X_pca[y==species, 1]
                   )

/home/chris/.local/lib/python3.8/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/chris/.local/lib/python3.8/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/chris/.local/lib/python3.8/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(


In [53]:
mapping = {
    'Iris-setosa' : 1,
    'Iris-versicolor' : 2,
    'Iriss-virginica' : 3
}

X = data.drop(['Species'], axis=1).values # Input Feature Values
y = data.Species.replace(mapping).values.reshape(rows,1) # Output values

X = np.hstack(((np.ones((rows,1))), X))# Adding one more column for bias

KeyError: "['Species'] not found in axis"